const RestaurantObject = {
  restaurants: [
    {
      id: "231204",
      name: "Burger King",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      locality: "Hazratganj",
      areaName: "Hazratganj",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4.1,
      parentId: "166",
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 22,
        lastMileTravel: 1,
        serviceability: "SERVICEABLE",
        slaString: "22 mins",
        lastMileTravelString: "1.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
    {
      id: "60379",
      name: "Pizza Hut",
      cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
      locality: "Saharaganj Mall",
      areaName: "Hazratganj",
      costForTwo: "₹350 for two",
      cuisines: ["Pizzas"],
      avgRating: 4,
      parentId: "721",
      avgRatingString: "4.0",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 35,
        lastMileTravel: 1.8,
        serviceability: "SERVICEABLE",
        slaString: "35 mins",
        lastMileTravelString: "1.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
    {
      id: "461532",
      name: "Starbucks Coffee",
      cloudinaryImageId: "0c958153eeb436db6d515ca36e47e8a4",
      locality: "Shagun Palace",
      areaName: "Sapru Marg",
      costForTwo: "₹400 for two",
      cuisines: [
        "Beverages",
        "Cafe",
        "Snacks",
        "Desserts",
        "Bakery",
        "Ice Cream",
      ],
      avgRating: 3.9,
      parentId: "195515",
      avgRatingString: "3.9",
      totalRatingsString: "500+",
      sla: {
        deliveryTime: 22,
        lastMileTravel: 0.7,
        serviceability: "SERVICEABLE",
        slaString: "22 mins",
        lastMileTravelString: "0.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
    {
      id: "758098",
      name: "7th Heaven",
      cloudinaryImageId: "d4057f18998ec90ea1855895d37db730",
      locality: "Ekta Vihar",
      areaName: "Mahanagar",
      costForTwo: "₹150 for two",
      cuisines: ["Bakery"],
      avgRating: 4.8,
      veg: true,
      parentId: "19",
      avgRatingString: "4.8",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 38,
        lastMileTravel: 6.4,
        serviceability: "SERVICEABLE",
        slaString: "38 mins",
        lastMileTravelString: "6.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
    {
      id: "59824",
      name: "Mashi Biryani World",
      cloudinaryImageId: "q0t8dkpigeideecc1hun",
      locality: "BN Road",
      areaName: "Lalbagh",
      costForTwo: "₹150 for two",
      cuisines: ["North Indian", "Biryani"],
      avgRating: 4,
      parentId: "6332",
      avgRatingString: "4.0",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 27,
        lastMileTravel: 1.9,
        serviceability: "SERVICEABLE",
        slaString: "27 mins",
        lastMileTravelString: "1.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
    {
      id: "532693",
      name: "McDonald's",
      cloudinaryImageId: "6dc3ed2ca21d71acff7c2a51dfe4c720",
      locality: "Habibullah Estate Road",
      areaName: "Hazratganj",
      costForTwo: "₹400 for two",
      cuisines: ["American"],
      avgRating: 4.1,
      parentId: "630",
      avgRatingString: "4.1",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 25,
        lastMileTravel: 1.7,
        serviceability: "SERVICEABLE",
        slaString: "25 mins",
        lastMileTravelString: "1.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
    {
      id: "635227",
      name: "Bakingo",
      cloudinaryImageId: "0c53fd8f62e3d25ba56d1b4cfe572cef",
      locality: "Gokhle Marg",
      areaName: "Hazratganj",
      costForTwo: "₹299 for two",
      cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
      avgRating: 4.5,
      parentId: "3818",
      avgRatingString: "4.5",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 34,
        lastMileTravel: 3,
        serviceability: "SERVICEABLE",
        slaString: "34 mins",
        lastMileTravelString: "3.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
    {
      id: "59941",
      name: "Marksmen",
      cloudinaryImageId: "tezzkxsqjop8fhxc9cqt",
      locality: "Lalbagh",
      areaName: "Lalbagh",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "South Indian", "Fast Food"],
      avgRating: 4.1,
      parentId: "132694",
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 34,
        lastMileTravel: 1.7,
        serviceability: "SERVICEABLE",
        slaString: "34 mins",
        lastMileTravelString: "1.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
    {
      id: "59122",
      name: "Sardar Ji Ke Mashoor Chhole Bhature",
      cloudinaryImageId: "f19fe5dd4320865a2dd675d940d92d31",
      locality: "Lalbagh",
      areaName: "Lalbagh",
      costForTwo: "₹50 for two",
      cuisines: ["North Indian", "Punjabi"],
      avgRating: 4.1,
      parentId: "6646",
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 27,
        lastMileTravel: 1.6,
        serviceability: "SERVICEABLE",
        slaString: "27 mins",
        lastMileTravelString: "1.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
    },
  ],
};

export default RestaurantObject;
